### ISSUE TITLE
at4 have draw_empty missing for 1.4

### ISSUE THREAD

**Issue by svcino** [KernCore91/-SC-Insurgency-Weapons-Project#1]
ERROR: Angelscript: g:/steamlibrary/steamapps/common/sven co-op/svencoop_addon/scripts/maps/ins2/explo/weapon_ins2at4.as (151, 65) : No matching symbol 'DRAW_EMPTY'

**Comment by KernCore91** [comment]
Fixed and updated. Thanks for reporting.
