### ISSUE TITLE
Getting all weapons with a single command...

### ISSUE THREAD

**Issue by hlepnamingblyat** [KernCore91/-SC-Insurgency-Weapons-Project#11]
Is it possible to use impulse 101 and get them all, or is there other command that does so?

**Comment by KernCore91** [comment]
Have this [pastebin](https://pastebin.com/uxVXL8q8).  
Save it as **ins2_weapons.cfg** inside your _svencoop_addon_ folder.  
Just type in the console `exec ins2_weapons.cfg` with sv_cheats and they will be given to you.

**Comment by hlepnamingblyat** [comment]
> 

Nice, thx.
And what if I want more ammo? Should I exec the same thing?

**Comment by hlepnamingblyat** [comment]
> Have this [pastebin](https://pastebin.com/uxVXL8q8).
Save it as ins2_weapons.cfg inside your svencoop_addon folder.
Just type in the console exec ins2_weapons.cfg with sv_cheats and they will be given to you.

> Nice, thx. And what if I want more ammo? Should I exec the same thing?

**Comment by hlepnamingblyat** [comment]
> Have this [pastebin](https://pastebin.com/uxVXL8q8). Save it as **ins2_weapons.cfg** inside your _svencoop_addon_ folder. Just type in the console `exec ins2_weapons.cfg` with sv_cheats and they will be given to you.

Nice, thx.
What if I want more ammo? Should I exec the same thing?
Edit: it says that it couldn't exec it.
Edit2: no, scratch it, it's done. I just wanna know if there's a way to fill everything with ammo in one press or command.

**Comment by KernCore91** [comment]
> > Have this [pastebin](https://pastebin.com/uxVXL8q8). Save it as **ins2_weapons.cfg** inside your _svencoop_addon_ folder. Just type in the console `exec ins2_weapons.cfg` with sv_cheats and they will be given to you.
> 
> Nice, thx. What if I want more ammo? Should I exec the same thing? Edit: it says that it couldn't exec it. Edit2: no, scratch it, it's done. I just wanna know if there's a way to fill everything with ammo in one press or command.

If I remember correctly AFB should offer you a cvar that gives you ammo for every weapon equipped.

**Comment by hlepnamingblyat** [comment]
> > > Have this [pastebin](https://pastebin.com/uxVXL8q8). Save it as **ins2_weapons.cfg** inside your _svencoop_addon_ folder. Just type in the console `exec ins2_weapons.cfg` with sv_cheats and they will be given to you.
> > 
> > 
> > Nice, thx. What if I want more ammo? Should I exec the same thing? Edit: it says that it couldn't exec it. Edit2: no, scratch it, it's done. I just wanna know if there's a way to fill everything with ammo in one press or command.
> 
> If I remember correctly AFB should offer you a cvar that gives you ammo for every weapon equipped.


I managed to do the exec command and if I repeat the same command over and over, it will eventually reach full ammo capacity. If I need more ammo, I just buy it without any issues since I increased the money veeery much :D 
And thx for this, it gives a much bigger choice in weaponry.
Oh, and are there any future weapons to be added?

**Comment by KernCore91** [comment]
> > > > Have this [pastebin](https://pastebin.com/uxVXL8q8). Save it as **ins2_weapons.cfg** inside your _svencoop_addon_ folder. Just type in the console `exec ins2_weapons.cfg` with sv_cheats and they will be given to you.
> > > 
> > > 
> > > Nice, thx. What if I want more ammo? Should I exec the same thing? Edit: it says that it couldn't exec it. Edit2: no, scratch it, it's done. I just wanna know if there's a way to fill everything with ammo in one press or command.
> > 
> > 
> > If I remember correctly AFB should offer you a cvar that gives you ammo for every weapon equipped.
> 
> I managed to do the exec command and if I repeat the same command over and over, it will eventually reach full ammo capacity. If I need more ammo, I just buy it without any issues since I increased the money veeery much :D And thx for this, it gives a much bigger choice in weaponry. Oh, and are there any future weapons to be added?

There will be more. Unfortunately I am dealing with health issues and other team members are busy with real life work.

**Comment by hlepnamingblyat** [comment]
> > > > > Have this [pastebin](https://pastebin.com/uxVXL8q8). Save it as **ins2_weapons.cfg** inside your _svencoop_addon_ folder. Just type in the console `exec ins2_weapons.cfg` with sv_cheats and they will be given to you.
> > > > 
> > > > 
> > > > Nice, thx. What if I want more ammo? Should I exec the same thing? Edit: it says that it couldn't exec it. Edit2: no, scratch it, it's done. I just wanna know if there's a way to fill everything with ammo in one press or command.
> > > 
> > > 
> > > If I remember correctly AFB should offer you a cvar that gives you ammo for every weapon equipped.
> > 
> > 
> > I managed to do the exec command and if I repeat the same command over and over, it will eventually reach full ammo capacity. If I need more ammo, I just buy it without any issues since I increased the money veeery much :D And thx for this, it gives a much bigger choice in weaponry. Oh, and are there any future weapons to be added?
> 
> There will be more. Unfortunately I am dealing with health issues and other team members are busy with real life work.


Ooh man... Wish you and your team the best. Stay safe brother.
