### ISSUE TITLE
Weapons reloads

### ISSUE THREAD

**Issue by TEXHAPb777** [KernCore91/-SC-Insurgency-Weapons-Project#16]
Every weapons have annoying delay after shooting last bullet, all time i hit reload button in this moment and weapon not reload. If you have more than 0 bullet its reload normaly w/o delays. This issue force you to mashing reload button twice or more. Why it cant work normaly if i press once after releasing last bullet?

**Comment by KernCore91** [comment]
I suppose modifying this [line](https://github.com/KernCore91/-SC-Insurgency-Weapons-Project/blob/master/scripts/maps/ins2/base.as#L768-L769) will give you better results?

**Comment by TEXHAPb777** [comment]
Thanks, its working fine with 0.1.
> I suppose modifying this [line](https://github.com/KernCore91/-SC-Insurgency-Weapons-Project/blob/master/scripts/maps/ins2/base.as#L768-L769) will give you better results?
