### ISSUE TITLE
HUD sprites show up as player arms

### ISSUE THREAD

**Issue by Aoi-the-Hert** [KernCore91/-SC-Insurgency-Weapons-Project#5]
Sometimes after changing maps the weapon HUD icons show up as the player's arms and sometimes they're just blank. Any ideas on how to fix?

(AWESOME WORK BTW APPRECIATE IT)
![image](https://user-images.githubusercontent.com/12159393/119240104-50d76c00-bb13-11eb-91fd-a754001ae149.png)
![image](https://user-images.githubusercontent.com/12159393/119240154-9f850600-bb13-11eb-9aa7-24223a15d344.png)
![image](https://user-images.githubusercontent.com/12159393/119240165-a744aa80-bb13-11eb-9912-081dcadc28d0.png)
![image](https://user-images.githubusercontent.com/12159393/119240173-af9ce580-bb13-11eb-8265-483f9a1f255c.png)
![image](https://user-images.githubusercontent.com/12159393/119240184-b75c8a00-bb13-11eb-8aaf-ad6e33fbd992.png)

**Comment by KernCore91** [comment]
I unfortunately can't fix that.  
I have reported this issue to the Developers, as I have also experienced it when restarting levels using votes (ie.: classic mode/survival restart).  
Thanks for reminding me again about it.

**Comment by Aoi-the-Hert** [comment]
Any information that would be useful in solving the issue? Or rather anything i can do to help solve it?

**Comment by KernCore91** [comment]
Unfortunately no, sorry.  
This is an issue with the OpenGL API itself, and so only engine developers are able to look into it.  
The issue is already on our bug tracker with a way to reproduce it, so no need to worry about it.
