### ISSUE TITLE
Failed to initialize global variable 'g_Ins2ItemMappings'

### ISSUE THREAD

**Issue by undergroundflower** [KernCore91/-SC-Insurgency-Weapons-Project#6]
Hi, I have made some replacement map scripts, but sometimes they work perfectly sometimes they failed to compile.

The only error message is "Failed to initialize global variable 'g_Ins2ItemMappings'"

The script is [here](https://paste.0xfc.de/?56e1c96d44f31c90#FduerXC3HxSQPEpbxzX4EYigSGR1ijsPfwvbDFZLg77x)

**Comment by KernCore91** [comment]
First thing I noticed was the First line with `replacement map script` not being commented.  
I tried it out after removing it and it worked just fine, although I'd like to point out a few issues I found.  

Line 83:
```
{ INS2_DEAGLE::GetName(), INS2_DEAGLE::GetAmmoName() },
```
Last array item has a `,`. If it has a `,` the ItemMapping Array will think there is another item after that one, and will sometimes use a null item.

---
Line 88:
```
INS2_M29::GetName(),
```
Same as above.

**Comment by undergroundflower** [comment]
Thanks for your replay!
The first line not being commented was a paste error, the script file was fine.
I fixed line 83 and line 88, it works fine now.

Is weird that even with syntax error on line 83 and line 88, the script can sometimes successfully compile.
