### ISSUE TITLE
Issue with the weapons.

### ISSUE THREAD

**Issue by MeGo1911** [KernCore91/-SC-Insurgency-Weapons-Project#8]
The weapons works perfectly, however am having some trouble re-compiling them after I done some viewmodel origin edits .
You see I have this strange issue, somehow I am able to compile some weapons with no issues. But other weapons I encounter an error saying: Texture too large.
I used 3 different compilers but still the same error .
![asdwefwefwefwef](https://user-images.githubusercontent.com/69175792/126894432-1ad1439b-81ed-4ca2-a575-272b79009a24.PNG)
![ewfwefwefwef](https://user-images.githubusercontent.com/69175792/126894435-1d6c8cd6-9426-4cdd-852c-74c2df9d0eef.PNG)

**Comment by KernCore91** [comment]
Use Sven's studiomdl that comes in the Sven Co-op SDK.  
Sven Co-op supports up to 1024x1024 textures resolutions since patch 5.17 if I remember correctly.  
You can find it in the Tools section on Steam

**Comment by MeGo1911** [comment]
Thank you for your help. It worked.
